---
:concurrency: 10
:queues:
  - schedule_deliveries
  - send_deliveries
  - sync_campaigns
  - sync_corporations
  - sync_lists
:schedule: {}
  # SendAllScheduledDeliveriesWorker:
  #   every: ['1m', first_in: '0s']

  # SyncAllCorporationMembersWorker:
  #   every: ['1h', first_in: '0s']
